# Generated by Django 5.2.6 on 2025-09-11 11:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('source', models.FileField(upload_to='video/source/', verbose_name='Исходник')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('processing', 'Обработка'), ('ready', 'Готово'), ('failed', 'Ошибка')], db_index=True, default='queued', max_length=16, verbose_name='Статус')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='video/posters/', verbose_name='Постер')),
                ('m3u8_url', models.CharField(blank=True, max_length=500, verbose_name='Плейлист HLS')),
                ('out_dir', models.CharField(blank=True, max_length=500, verbose_name='Папка результата')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['-created'],
            },
        ),
    ]
