# Generated by Django 5.2.6 on 2025-09-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Показывать в hero'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(condition=models.Q(('is_featured', True)), fields=('is_featured',), name='only_one_featured_video'),
        ),
    ]
