# Generated by Django 5.2.6 on 2025-09-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_is_featured_video_only_one_featured_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Хэш исходника'),
        ),
    ]
