# Generated by Django 5.2.6 on 2025-09-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_video_source_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='source_hash',
        ),
    ]
