# Generated by Django 5.2.6 on 2025-09-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Показывать на главной'),
        ),
    ]
