# Generated by Django 5.2.6 on 2025-09-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_news_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('placement', 'position', '-created'), 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.RemoveConstraint(
            model_name='video',
            name='only_one_featured_video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='video',
            name='placement',
            field=models.CharField(choices=[('hero', 'Hero'), ('gallery', 'Видеогалерея'), ('block', 'Видеоблок')], db_index=True, default='gallery', max_length=12, verbose_name='Размещение'),
        ),
        migrations.AddField(
            model_name='video',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Работает для видеогалереи и видеоблока', verbose_name='Порядок в группе'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(condition=models.Q(('placement', 'hero')), fields=('placement',), name='only_one_hero_video'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(condition=models.Q(('position__gt', 0)), fields=('placement', 'position'), name='unique_position_per_group'),
        ),
    ]
