# Generated by Django 5.2.6 on 2025-09-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_video_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('file', models.FileField(upload_to='pdf/', verbose_name='ПДФ')),
            ],
            options={
                'verbose_name': 'PDF файл',
                'verbose_name_plural': 'PDF файлы',
            },
        ),
    ]
