name: build-and-push
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  web:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Check secrets & paths
        run: |
          test -n "$DOCKERHUB_USERNAME" || (echo "DOCKERHUB_USERNAME is empty" && exit 1)
          test -n "$DOCKERHUB_TOKEN" || (echo "DOCKERHUB_TOKEN is empty" && exit 1)
          test -f ./app/Dockerfile || (echo "Dockerfile not found at ./app/Dockerfile" && ls -la ./app && exit 1)

      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          pull: true
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/crosswell-corp-web-1:latest
            ${{ env.DOCKERHUB_USERNAME }}/crosswell-corp-web-1:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/crosswell-corp-web-1:buildcache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/crosswell-corp-web-1:buildcache,mode=max
