# Generated by Django 5.2.6 on 2025-09-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='portfolio/icons/', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='portfolio/icons/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='case',
            name='photo',
            field=models.ImageField(upload_to='portfolio/cases/', verbose_name='Фото'),
        ),
    ]
