# Generated by Django 5.2.6 on 2025-09-17 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cases.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, upload_to='portfolio/subcategories/', verbose_name='Фото')),
                ('icon', models.ImageField(blank=True, upload_to='portfolio/subcategories/', verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cases.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cases.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['category', 'order'], name='cases_case_categor_cad307_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['subcategory', 'order'], name='cases_case_subcate_0dd7b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('subcategory__isnull', True)), models.Q(('category__isnull', True), ('subcategory__isnull', False)), _connector='OR'), name='case_category_xor_subcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
    ]
