# Generated by Django 5.2.6 on 2025-09-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_case_category_subcategory_case_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='photo',
        ),
    ]
