# Generated by Django 5.2.7 on 2025-11-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_remove_subcategory_icon_remove_subcategory_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='effects',
            field=models.FileField(blank=True, upload_to='portfolio/effects/', verbose_name='Эффекты (WEBM)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, upload_to='portfolio/icons/', verbose_name='Иконка (изображение или WEBM)'),
        ),
    ]
