# Generated by Django 5.2.6 on 2025-09-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqsRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Получатель заявок',
                'verbose_name_plural': 'Получатели заявок',
                'ordering': ['-is_active', 'email'],
            },
        ),
    ]
